# Minimal Avahi configuration for the Shairport Sync add-on.
# Shairport Sync talks to Avahi over D-Bus to publish the AirPlay service.

[server]
enable-dbus=yes
use-ipv4=yes
use-ipv6=yes
allow-interfaces=eth0,eth1,wlan0,wlan1,enp*,wlan*,end*,en*,wl*
publish-hinfo=no
publish-workstation=no

[wide-area]
enable-wide-area=yes

[publish]
disable-publishing=no
disable-user-service-publishing=no

[reflector]
enable-reflector=no

[cups]
browse-domains=
